import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Job Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 nav-w-3xl">
        <div className="flex justify-around p-3 gap-3">
          <h2 className="text-2xl font-semibold">My applications</h2>
          <button type='button' className="bg-blue-400 text-sm rounded-md transition p-2 hover:bg-blue-500">Add new job</button>


        </div>
        <div className="flex flex-wrap flex-row gap-4 mt-20 justify-center">
          <div className="flex flex-col gap-2">
          <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Job Name</label>
          <input type="text" id="small-input" className="block w-100 p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
          </div>
       
          <div className="flex flex-col gap-2">
          <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Job Name</label>
          <input type="text" id="small-input" className="block w-100 p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
          </div>
        
          <div className="flex flex-col gap-2">
          <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Job Name</label>
          <input type="text" id="small-input" className="block w-100 p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
          </div>
        
        
          <div className="flex flex-col gap-2">
          <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Job Name</label>
          <input type="text" id="small-input" className="block w-100 p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
